[build]
  command = "npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION        = "18"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"

[functions]
  directory = "netlify/functions"
  included_files = ["private/data/**"]

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200