import { useState, useEffect, useMemo } from 'react'

/**
 * Reads /data/chest_data.json — generated by sync_website.py
 * Returns { weeks, currentWeek, setWeekIndex, weekIndex, loading, error }
 */
export function useChestData() {
  const [raw, setRaw]         = useState(null)
  const [weekIndex, setWeekIndex] = useState(0)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState(null)

  useEffect(() => {
    fetch('/data/chest_data.json')
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then(data => { setRaw(data); setLoading(false) })
      .catch(e  => { setError(e.message); setLoading(false) })
  }, [])

  const weeks        = raw?.weeks         || []
  const chestColumns = raw?.chest_columns || []
  const scoring      = raw?.scoring       || {}
  const weeklyTarget = raw?.weekly_target || 1000
  const currentWeek  = weeks[weekIndex]   || null

  return {
    weeks, chestColumns, scoring, weeklyTarget,
    weekIndex, setWeekIndex,
    currentWeek,
    loading, error,
    generated: raw?.generated || null,
  }
}